config/routes.rb
Rails.application.routes.draw do
  root 'users#new' 
  resources :users do
    member do
      get 'generate_otp'
      post 'verify_otp'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  before_create :generate_otp_secret

  private

  def generate_otp_secret
    self.otp_secret = ROTP::Base32.random_base32
  end
end

  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:generate_otp, :verify_otp]

  def new
    @user = User.new
  end

  def generate_otp
    @otp = ROTP::TOTP.new(@user.otp_secret)
  end

  def verify_otp
    @otp = ROTP::TOTP.new(@user.otp_secret)
    @verification_result = @otp.verify(params[:otp])

    respond_to do |format|
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OtpSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/generate_otp.html.erb
<p>OTP: <%= @otp.now %></p>

<%= form_with(model: @user, url: verify_otp_user_path(@user), method: :post, remote: true) do |form| %>
  <%= form.label :otp %>
  <%= form.text_field :otp %>

  <%= form.submit 'Verify OTP' %>
<% end %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.email_field :email %>

  <%= form.submit 'Generate OTP' %>
<% end %>

app/views/users/verify_otp.html.erb
<% if @verification_result %>
  alert('OTP verified successfully!');
<% else %>
  alert('OTP verification failed. Please try again.');
<% end %>